(defun sdl () 
  (let ((color sdl:*black*))
    (sdl:with-init ()
      (sdl:window 320 240)
      (sdl:clear-display color)
      (setf (sdl:frame-rate) 30)
      (sdl:with-events ()
	(:quit-event () t)
	(:video-expose-event () (sdl:update-display))
	(:idle () 
	       (idle)
	       (sdl:update-display))))))

(defun idle ()
  (break "~a" sdl:*default-color*))